version: '3'

services:
  nginx: #服务名称
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /root/nginx/html:/user/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=8871527
  redis:
    image: redis:latest
  vueblog:
    image: vueblog:latest
    build: ..
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - redis